import Foundation

enum Constants {
    static let trackerCoreData = "TrackerCoreData"
    static let trackerCategoryData = "TrackerCategoryCoreData"
    static let onboardRedScreen = "onboardRedScreen"
    static let onboardBlueScreen = "onboardBlueScreen"
    static let onboardRedText = "Даже если это не литры воды и йога"
    static let onboardBlueText = "Отслеживайте только то, что хотите"
    static let deleteTracker = "Уверены что хотите удалить трекер?"
    static let pin = "Закрепить"
    static let edit = "Редактировать"
    static let delete = "Удалить"
    static let cancelAlert = "Отмена"
    static let done = "Готово"
    static let create = "Создать"
    static let cancel = "Отменить"
    static let search = "Поиск"
    static let trackerEmptyLogo = "Что будем отслеживать?"
    static let filters = "Фильтры"
    static let trackers = "Трекеры"
    static let statistic = "Статистика"
    static let wowTechs = "Вот это технологии!"
    static let nothingToAnalyze = "Анализировать пока нечего"
    static let habit = "Привычка"
    static let unregularEvent = "Нерегулярное событие"
    static let createTracker = "Создание трекера"
    static let color = "Цвет"
    static let enterTrackerName = "Введите название трекера"
    static let newHabit = "Новая привычка"
    static let newUnregularEvent = "Новое нерегулярное событие"
    static let schedule = "Расписание"
    static let addCategory = "Добавить категорию"
    static let emptyCategory = "Привычки и события можно \n объединить по смыслу"
    static let category = "Категория"
    static let enterCategory = "Введите название категории"
    static let warningLabel = "Ограничение 38 символов"
}
